# ~/.config/starship.toml

add_newline = false
format = """
[](#a3aed2)\
$directory\
[](bg:#f7768e fg:#a3aed2)\
$git_branch\
$git_status\
[](bg:#44475a fg:#f7768e)\
$nodejs\
$python\
$docker_context\
$cmd_duration\
[](fg:#44475a)\
$character
"""

[directory]
style = "bg:#a3aed2 fg:#1e1e2e"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#f7768e fg:#1e1e2e"
symbol = ""

[git_status]
style = "bg:#f7768e fg:#1e1e2e"
format = "([$all_status$ahead_behind ]($style))"

[character]
success_symbol = "[](bold fg:#50fa7b)"
error_symbol = "[](bold fg:#ff5555)"
